version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  worker:
    build: .
    command: celery -A app.workers.worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
  dashboard:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis